name: mahmc
channels:
  - defaults
dependencies:
  - arviz=0.11.2
  - joblib=1.1.0
  - jupyter=1.0.0
  - matplotlib=3.5.0
  - numba=0.54.1
  - numpy=1.20.3
  - pip=21.2.4
  - python=3.8
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tqdm=4.62.3
  - pip:
    - jax==0.2.26
    - jaxlib==0.1.75
